# Generated by Django 3.1.2 on 2020-10-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20201011_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
