# Generated by Django 3.1.2 on 2020-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_image_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
